# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail.proto',
  package='protomail',
  syntax='proto3',
  serialized_options=b'Z\n/protomail',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmail.proto\x12\tprotomail\"\x07\n\x05\x45mpty\"B\n\x0e\x43onnectRequest\x12\x10\n\x08\x63lientid\x18\x01 \x01(\x04\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0e\n\x06useTLS\x18\x03 \x01(\x08\"(\n\x0f\x43onnectResponce\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\"I\n\x0cLoginRequest\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\"&\n\rDeleteRequest\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\"-\n\x14ListMailboxesRequest\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\",\n\x15ListMailboxesResponce\x12\x13\n\x0bmailboxName\x18\x01 \x01(\t\"T\n\x14SelectMailboxRequest\x12\x15\n\rclientPointer\x18\x01 \x01(\x04\x12\x13\n\x0bmailboxName\x18\x02 \x01(\t\x12\x10\n\x08readonly\x18\x03 \x01(\x08\x32\x9a\x03\n\x04Mail\x12\x46\n\rConnectClient\x12\x19.protomail.ConnectRequest\x1a\x1a.protomail.ConnectResponce\x12\x38\n\x0bLoginClient\x12\x17.protomail.LoginRequest\x1a\x10.protomail.Empty\x12:\n\x0cLogoutClient\x12\x18.protomail.LogoutRequest\x1a\x10.protomail.Empty\x12:\n\x0c\x44\x65leteClient\x12\x18.protomail.DeleteRequest\x1a\x10.protomail.Empty\x12T\n\rListMailboxes\x12\x1f.protomail.ListMailboxesRequest\x1a .protomail.ListMailboxesResponce0\x01\x12\x42\n\rSelectMailbox\x12\x1f.protomail.SelectMailboxRequest\x1a\x10.protomail.EmptyB\x0cZ\n/protomailb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='protomail.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=32,
)


_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='protomail.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientid', full_name='protomail.ConnectRequest.clientid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server', full_name='protomail.ConnectRequest.server', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='useTLS', full_name='protomail.ConnectRequest.useTLS', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=100,
)


_CONNECTRESPONCE = _descriptor.Descriptor(
  name='ConnectResponce',
  full_name='protomail.ConnectResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.ConnectResponce.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=142,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='protomail.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.LoginRequest.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='protomail.LoginRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='protomail.LoginRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=217,
)


_LOGOUTREQUEST = _descriptor.Descriptor(
  name='LogoutRequest',
  full_name='protomail.LogoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.LogoutRequest.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=257,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='protomail.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.DeleteRequest.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=297,
)


_LISTMAILBOXESREQUEST = _descriptor.Descriptor(
  name='ListMailboxesRequest',
  full_name='protomail.ListMailboxesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.ListMailboxesRequest.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=344,
)


_LISTMAILBOXESRESPONCE = _descriptor.Descriptor(
  name='ListMailboxesResponce',
  full_name='protomail.ListMailboxesResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mailboxName', full_name='protomail.ListMailboxesResponce.mailboxName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=390,
)


_SELECTMAILBOXREQUEST = _descriptor.Descriptor(
  name='SelectMailboxRequest',
  full_name='protomail.SelectMailboxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientPointer', full_name='protomail.SelectMailboxRequest.clientPointer', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mailboxName', full_name='protomail.SelectMailboxRequest.mailboxName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='readonly', full_name='protomail.SelectMailboxRequest.readonly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=476,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponce'] = _CONNECTRESPONCE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LogoutRequest'] = _LOGOUTREQUEST
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['ListMailboxesRequest'] = _LISTMAILBOXESREQUEST
DESCRIPTOR.message_types_by_name['ListMailboxesResponce'] = _LISTMAILBOXESRESPONCE
DESCRIPTOR.message_types_by_name['SelectMailboxRequest'] = _SELECTMAILBOXREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.Empty)
  })
_sym_db.RegisterMessage(Empty)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponce = _reflection.GeneratedProtocolMessageType('ConnectResponce', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONCE,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.ConnectResponce)
  })
_sym_db.RegisterMessage(ConnectResponce)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LogoutRequest = _reflection.GeneratedProtocolMessageType('LogoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGOUTREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.LogoutRequest)
  })
_sym_db.RegisterMessage(LogoutRequest)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

ListMailboxesRequest = _reflection.GeneratedProtocolMessageType('ListMailboxesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTMAILBOXESREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.ListMailboxesRequest)
  })
_sym_db.RegisterMessage(ListMailboxesRequest)

ListMailboxesResponce = _reflection.GeneratedProtocolMessageType('ListMailboxesResponce', (_message.Message,), {
  'DESCRIPTOR' : _LISTMAILBOXESRESPONCE,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.ListMailboxesResponce)
  })
_sym_db.RegisterMessage(ListMailboxesResponce)

SelectMailboxRequest = _reflection.GeneratedProtocolMessageType('SelectMailboxRequest', (_message.Message,), {
  'DESCRIPTOR' : _SELECTMAILBOXREQUEST,
  '__module__' : 'mail_pb2'
  # @@protoc_insertion_point(class_scope:protomail.SelectMailboxRequest)
  })
_sym_db.RegisterMessage(SelectMailboxRequest)


DESCRIPTOR._options = None

_MAIL = _descriptor.ServiceDescriptor(
  name='Mail',
  full_name='protomail.Mail',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=479,
  serialized_end=889,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectClient',
    full_name='protomail.Mail.ConnectClient',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoginClient',
    full_name='protomail.Mail.LoginClient',
    index=1,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LogoutClient',
    full_name='protomail.Mail.LogoutClient',
    index=2,
    containing_service=None,
    input_type=_LOGOUTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteClient',
    full_name='protomail.Mail.DeleteClient',
    index=3,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListMailboxes',
    full_name='protomail.Mail.ListMailboxes',
    index=4,
    containing_service=None,
    input_type=_LISTMAILBOXESREQUEST,
    output_type=_LISTMAILBOXESRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SelectMailbox',
    full_name='protomail.Mail.SelectMailbox',
    index=5,
    containing_service=None,
    input_type=_SELECTMAILBOXREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAIL)

DESCRIPTOR.services_by_name['Mail'] = _MAIL

# @@protoc_insertion_point(module_scope)
